spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 3000
      validation-timeout: 1000
      max-lifetime: 1700000
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  address: 127.0.0.1
  servlet:
    session:
      cookie:
        secure: true
